<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="GitVersion.MsBuild" Version="6.6.1" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.5" />
    <PackageVersion Include="Microsoft.VisualStudio.Threading.Only" Version="17.14.15" />
  </ItemGroup>
</Project>